package boundary;

public class FeltBeskrivelser {
	// Laver et array med felt navne
	public static String[] fieldNames = {
				"Start",
				"Rødovrevej",
				"Prøv lykken",
				"Hvidovrevej", 
				"Indkomst skat",
				"Scandlines Helsingør-Helsingborg", 
				"Roskildevej",
				"Prøv lykken", 
				"Valby Langgade", 
				"Allégade",
				"Fængsel", 
				"Frederiksberg Allé",
				"Tuborg Squash",
				"Bülowsvej", 
				"Gl.Kongevej",
				"Mols-linien", 
				"Bernstorffsvej",
				"Prøv lykken", 
				"Hellerupvej", 
				"Strandvejen",
				"Parkering", 
				"Trianglen",
				"Prøv lykken",
				"Østerbrogade",
				"Grønningen",
				"Scandlines Gedser-Rostock",
				"Bredgade",
				"Kgs.Nytorv",
				"Coca-Cola",
				"Østergade",
				"De fængsles",
				"Amagertorv",
				"Vimmelskaftet",
				"Prøv lykken",
				"Nygade",
				"Scandlines Rødby-Puttgarden",
				"Prøv lykken",
				"Frederiksberggade",
				"Ekstraordinær statsskat",
				"Rådhuspladsen"
				};	
	public static int[] fieldValue = {
			0,
			1200,
			0,
			1200, 
			4000,
			4000, 
			2000, 
			0, 
			2000, 
			2400, 
			0, 
			2800,
			3000, 
			2800, 
			3200, 
			4000, 
			3600,
			0, 
			3600, 
			4000,
			0,
			4400,
			0,
			4400,
			4800,
			4000,
			5200,
			5200,
			3000,
			5600,
			0,
			6000,
			6000,
			0,
			6400,
			4000,
			0,
			7000,
			2000,
			8000
			};


}
